import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import providersRouter from "./providers.js";
import socialRouter from "./social.js";
import affiliatesRouter from "./affiliates.js";
import campaignsRouter from "./campaigns.js";
import systemEventsRouter from "./system-events.js";
import tasksRouter from "./tasks.js";
import brainRouter from "./brain.js";
import rulesRouter from "./rules.js";
import agentsRouter from "./agents.js";
import providerConfigsRouter from "./provider-configs.js";
import toolsRouter from "./tools.js";
import workflowsRouter from "./workflows.js";
import scheduledJobsRouter from "./scheduled-jobs.js";
import notificationsRouter from "./notifications.js";
import systemStatusRouter from "./system-status.js";
import auditLogRouter from "./audit-log.js";
import settingsRouter from "./settings.js";
import metricsRouter from "./metrics.js";
import { authRateLimiter } from "../middleware/security.js";
import profitEngineRouter from "./profit-engine.js";
import oauthRouter from "./oauth.js";
import webhooksRouter from "./webhooks.js";
import trendsRouter from "./trends.js";
import productsRouter from "./products.js";
import autonomousRouter from "./autonomous.js";
import youtubeOauthRouter from "./youtube-oauth.js";
import oauthProvidersRouter from "./oauth-providers.js";
import productionEngineRouter from "./production-engine.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(metricsRouter);
router.use(youtubeOauthRouter);
router.use(oauthProvidersRouter);
router.use(oauthRouter);
router.use(webhooksRouter);
router.use(trendsRouter);
router.use(productsRouter);
router.use(autonomousRouter);
router.use("/profit-engine", profitEngineRouter);
router.use("/production", productionEngineRouter);
router.use("/auth", authRateLimiter);
router.use(authRouter);
router.use(providersRouter);
router.use(socialRouter);
router.use(affiliatesRouter);
router.use(campaignsRouter);
router.use(systemEventsRouter);
router.use(tasksRouter);
router.use(brainRouter);
router.use(rulesRouter);
router.use(agentsRouter);
router.use(providerConfigsRouter);
router.use(toolsRouter);
router.use(workflowsRouter);
router.use(scheduledJobsRouter);
router.use(notificationsRouter);
router.use(systemStatusRouter);
router.use(auditLogRouter);
router.use(settingsRouter);

export default router;
